### ISSUE TITLE
希望能以一个blog系统，数据走ajax的简单实例来循序渐进的开讲下koa，国内资料太少

### ISSUE THREAD

**Issue by zb188** [minghe/koa-book#2]
希望能以一个blog系统，数据走ajax的简单实例来循序渐进的开讲下koa，内资料太少
最近后台系统项目准备用的做前后端完全分离，还有些东西不知道怎么入手

**Comment by minghe** [comment]
正在写~ http://book.apebook.org/minghe/koa-action/index.html
