### ISSUE TITLE
include() 引用子模板标签到底是三个{}还是两个？

### ISSUE THREAD

**Issue by cfanbo** [minghe/koa-book#6]
http://book.apebook.org/minghe/koa-action/xtemplate/senior.html

`include() 引用子模板
x.xtpl 与 y.xtpl 同级目录，y.xtpl 引用子模板x.tpl：

{{{include("x")}}}
留意是{{{}}}。`

但是发现用生成器生成的是模板用的是两个{}（官方的文档也是两个括号）。试了一下，用两个或者三个都一样的？

**Comment by minghe** [comment]
二个，三个是用于防止html内容转译
